name: Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/doc-deploy.yml"

env:
  LAF_CI_DOCS_PREVIEW_PAT: ${{ secrets.LAF_CI_DOCS_PREVIEW_PAT }}
  LAF_CI_DOCS_PREVIEW_APPID: ${{ secrets.LAF_CI_DOCS_PREVIEW_APPID }}
  LAF_CI_DOCS_PREVIEW_API_URL: ${{ secrets.LAF_CI_DOCS_PREVIEW_API_URL }}

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docs
        uses: ./.github/actions/build-docs

      - name: Setup data-plane-cli
        run: npm i data-plane-cli -g

      - name: Login data-plane-cli
        run: |
          data-plane user add doc -r ${{ env.LAF_CI_DOCS_PREVIEW_API_URL }}
          data-plane user switch doc
          data-plane login ${{ env.LAF_CI_DOCS_PREVIEW_PAT }}
          data-plane app init ${{ env.LAF_CI_DOCS_PREVIEW_APPID }}

      - name: Deploy to production bucket
        run: |
          # Deploy to production docs bucket
          data-plane storage push -f production-docs docs/.vitepress/dist/
